/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.admin;

import view.doctor.*;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import model.CityDirectory;
import model.Doctor;
import model.MainSystem;

/**
 *
 * @author adeda
 */
public class CRUDPatient extends javax.swing.JPanel {

    /**
     * Creates new form CRUDPatient
     */
    JPanel aPanel;
    CityDirectory allCities;
    Doctor attendingDoctor;
    private MainSystem mainSystem;
//    private JFrame aFrame;

    public CRUDPatient(MainSystem mainSystem) {
        initComponents();
        this.mainSystem = mainSystem;
        this.aPanel = mainSystem.getaPanel();
        this.allCities = mainSystem.getAllCities();
        this.attendingDoctor = mainSystem.getADoctor();
//        titleLabel.setText("Welcome Dr. " + attendingDoctor.getFirstName());
//        this.aFrame = mainSystem.getaFrame();
//        disableIrrelevantButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newPatientButton = new javax.swing.JButton();
        oldPatientButton = new javax.swing.JButton();
        choiceLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        newPatientButton.setText("Add Patient");
        newPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPatientButtonActionPerformed(evt);
            }
        });

        oldPatientButton.setText("View Patients");
        oldPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPatientButtonActionPerformed(evt);
            }
        });

        choiceLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        choiceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        choiceLabel.setText("Who do you want to attend to?");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addComponent(newPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(oldPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(318, 318, 318))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(choiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(backButton)
                .addGap(69, 69, 69)
                .addComponent(choiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(323, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPatientButtonActionPerformed
        // TODO add your handling code here:
        AddPatient addPatient = new AddPatient(mainSystem);
        aPanel.add(addPatient);
        CardLayout layout = (CardLayout) aPanel.getLayout();
        layout.next(aPanel);
    }//GEN-LAST:event_newPatientButtonActionPerformed

    private void oldPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldPatientButtonActionPerformed
        // TODO add your handling code here:
        ViewPatients viewPatients = new ViewPatients(mainSystem);
        aPanel.add(viewPatients);
        CardLayout layout = (CardLayout) aPanel.getLayout();
        layout.next(aPanel);
    }//GEN-LAST:event_oldPatientButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        SystemAdminDashboard sAPanel = new SystemAdminDashboard(mainSystem);
        aPanel.add(sAPanel);
        CardLayout layout = (CardLayout) aPanel.getLayout();
        layout.next(aPanel);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel choiceLabel;
    private javax.swing.JButton newPatientButton;
    private javax.swing.JButton oldPatientButton;
    // End of variables declaration//GEN-END:variables

//    private void disableIrrelevantButtons() {
//
//        JPanel freeLayoutPanel = mainSystem.getFreePanel();
//        Component[] components = freeLayoutPanel.getComponents();
//        for (Component component : components) {
//            if (component.getName().equals("doctorButton") | component.getName().equals("adminButton") | component.getName().equals("patientButton")) {
//                JButton myButton = (JButton) component;
//                myButton.setEnabled(false);
//            }
//        }
//    }
//
//    private void enableRelevantButtons() {
//        JPanel freeLayoutPanel = mainSystem.getFreePanel();
//        Component[] components = freeLayoutPanel.getComponents();
//        for (Component component : components) {
//            if (component.getName().equals("doctorButton") | component.getName().equals("adminButton") | component.getName().equals("patientButton")) {
//                JButton myButton = (JButton) component;
//                myButton.setEnabled(true);
//            }
//        }
//    }
}
